# Generated by Django 5.0.6 on 2024-05-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.CharField(max_length=100)),
                ('manufacture_year', models.PositiveIntegerField()),
                ('number_of_seats', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(max_length=10)),
                ('mileage', models.PositiveIntegerField()),
                ('quote_price', models.PositiveIntegerField()),
            ],
        ),
    ]
