# Generated by Django 5.0.6 on 2024-05-28 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_manufacturer_name_sell_mname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sell',
            old_name='mname',
            new_name='manufacturer_name',
        ),
    ]
